[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mcdc"
version = "0.9.0"
authors = [
  { name="Joanna Morgan", email="morgajoa@oregonstate.edu" },
]
description = "Monte Carlo / Dynamic Code, a pure python high preofmrance Monte Carlo neutronics package"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
keywords = ["egg", "bacon", "sausage", "tomatoes", "Lobster Thermidor"]
classifiers = [
    "Programming Language :: Python :: 3",
    'License :: OSI Approved :: BSD License',
    'Intended Audience :: Science/Research',
    'Typing :: Typed',
    'Natural Language :: English',
    'Operating System :: Unix',
    'Operating System :: MacOS',
]
dependencies = [
    "numba>=0.58.1",
    "numpy",
    "scipy",
    "matplotlib",
    "mpi4py>=3.1.5",
    "pytest",
    "h5py",
    "colorama",
]
[project.optional-dependencies]
    vis = ["ngsolve", "distinctipy"]
    docs = ["sphinx==7.2.6", "furo", "sphinx_toolbox"]



[project.urls]
Repository = "https://github.com/CEMeNT-PSAAP/MCDC"
Homepage = "https://cement-psaap.github.io/"
Documentation = "https://cement-psaapgithubio.readthedocs.io/en/latest/"
Issues = "https://github.com/CEMeNT-PSAAP/MCDC/issues"