name: Regression Test - Numba and MPI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: ["ubuntu-latest"] #, "macos-latest"
    steps:
    - uses: actions/checkout@v3
    - name: Set up python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: debug
      run: |
        pwd
        ls
    - uses: mpi4py/setup-mpi@v1
    - name: Install dependencies
      run: |
        #sudo apt-get install libopenmpi-dev
        #pip install numpy numba h5py matplotlib scipy pytest colorama mpi4py ngsolve distinctipy
        pip list 
        pip install -e .
    - name: Patch Numba
      run : |
        bash .github/workflows/patch.sh
    - name: Regression Test - Numba and MPI
      run: |
          cd test/regression
          python run.py --mode=numba --mpiexec=4
