name: Unit Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: ["ubuntu-22.04"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: debug
      run: |
        pwd
        ls
    - uses: mpi4py/setup-mpi@v1
    - name: Install dependencies
      run: |
        #sudo apt-get install libopenmpi-dev
        pip install numpy numba h5py matplotlib scipy pytest colorama mpi4py ngsolve distinctipy
        pip list 
        pip install -e .
    - name: Unit Test
      run : |
          pytest
